apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobquest-backend
  labels:
    app: jobquest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobquest-backend
  template:
    metadata:
      labels:
        app: jobquest-backend
    spec:
      containers:
      - name: jobquest-backend
        image: ${IBM_REGISTRY}/jobquest-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: jobquest-secrets
              key: mongodb_uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jobquest-secrets
              key: jwt_secret
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            configMapKeyRef:
              name: jobquest-config
              key: cloudinary_cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: jobquest-secrets
              key: cloudinary_api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: jobquest-secrets
              key: cloudinary_api_secret
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jobquest-backend
spec:
  selector:
    app: jobquest-backend
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP